export const SEED_DATA = [
  { rule_id: 1, category: "Rotation", when: "Any Element", "in": "Any Parent", "if": "Is Rotated (Value ≠ 0)", action: "Set Rotation", parameters: "Value: 0", summary: "Set Rotation | Value: 0", priority: 1, status: "Mapped", note: "Exception: Vertical Line excluded" },
  { rule_id: 2, category: "Hide / Show", when: "Vertical Line", "in": "Any Parent", "if": "Rotation = 270° / 90° (±)", action: "Set Visibility", parameters: "Value: Show", summary: "Set Visibility | Value: Show", priority: 1, status: "Mapped", note: "" },
  { rule_id: 3, category: "Hide / Show", when: "Vertical Line", "in": "Any Parent", "if": "Rotation ≠ 270° / 90° (±)", action: "Set Visibility", parameters: "Value: Hide", summary: "Set Visibility | Value: Hide", priority: 1, status: "Mapped", note: "" },
  { rule_id: 4, category: "Hide / Show", when: "Horizontal Line", "in": "Any Parent", "if": "Rotation ≠ 0 and ≠ 180", action: "Set Visibility", parameters: "Value: Hide", summary: "Set Visibility | Value: Hide", priority: 1, status: "Mapped", note: "" },
  { rule_id: 5, category: "Hide / Show", when: "Horizontal Line", "in": "Any Parent", "if": "Rotation = 0 or 180", action: "Set Visibility", parameters: "Value: Show", summary: "Set Visibility | Value: Show", priority: 1, status: "Mapped", note: "" },
  { rule_id: 6, category: "Content Order", when: "Any Container", "in": "Any Parent", "if": "Any", action: "Set OOG", parameters: "Arrangement: Vertical Arrange Children, Order: Z-shape", summary: "Set OOG | Arrangement: Vertical Arrange Children, Order: Z-shape", priority: 1, status: "Mapped", note: "" },
  { rule_id: 7, category: "Alignment", when: "Any Container", "in": "Any Parent", "if": "All Descendant Text Style: Left", action: "Set Alignment", parameters: "Value: Left", summary: "Set Alignment | Value: Left", priority: 1, status: "Mapped", note: "" },
  { rule_id: 8, category: "Alignment", when: "Any Container", "in": "Any Parent", "if": "All Descendant Text Style: Center", action: "Set Alignment", parameters: "Value: Center", summary: "Set Alignment | Value: Center", priority: 1, status: "Mapped", note: "" },
  { rule_id: 9, category: "Alignment", when: "Any Container", "in": "Any Parent", "if": "All Descendant Text Style: Right", action: "Set Alignment", parameters: "Value: Right", summary: "Set Alignment | Value: Right", priority: 1, status: "Mapped", note: "" },
  { rule_id: 10, category: "Alignment", when: "Any Container", "in": "Any Parent", "if": "All Descendant Text Style: Mixed AND Text Count > 3", action: "Set Alignment", parameters: "Value: Center", summary: "Set Alignment | Value: Center", priority: 1, status: "Mapped", note: "" },
  { rule_id: 11, category: "Image", when: "Image", "in": "Any Parent", "if": "Desktop Width: 0–200px", action: "Set Size", parameters: "Width: Keep Size, Height: Keep Size", summary: "Set Size | Width: Keep Size, Height: Keep Size", priority: 1, status: "Mapped", note: "" },
  { rule_id: 12, category: "Image", when: "Image", "in": "Any Parent", "if": "Desktop Width: 201px+", action: "Set Size", parameters: "Width: 100%, Height: Aspect Ratio", summary: "Set Size | Width: 100%, Height: Aspect Ratio", priority: 1, status: "Mapped", note: "" },
  { rule_id: 13, category: "Horizontal Line", when: "Horizontal Line", "in": "Any Parent", "if": "Desktop Width: 1px–199px", action: "Set Size", parameters: "Width: Keep Size, Height: Auto", summary: "Set Size | Width: Keep Size, Height: Auto", priority: 1, status: "Mapped", note: "" },
  { rule_id: 14, category: "Horizontal Line", when: "Horizontal Line", "in": "Any Parent", "if": "Desktop Width: 200px+", action: "Set Size", parameters: "Width: 100%, Height: Auto", summary: "Set Size | Width: 100%, Height: Auto", priority: 1, status: "Mapped", note: "" },
  { rule_id: 15, category: "Shape (SVG)", when: "Hamburger Menu | Shape", "in": "Any Parent", "if": "Desktop Width: 1px–100px", action: "Set Size", parameters: "Width: Keep Size, Height: Keep Size", summary: "Set Size | Width: Keep Size, Height: Keep Size", priority: 1, status: "Mapped", note: "" },
  { rule_id: 16, category: "Shape (SVG)", when: "Hamburger Menu | Shape", "in": "Any Parent", "if": "Desktop Width: 101px+ → Resize Aspect Ratio", action: "Set Size", parameters: "Resize: Aspect Ratio (reduce 30%), Min Width: 43px", summary: "Set Size | Resize: Aspect Ratio (reduce 30%), Min Width: 43px", priority: 1, status: "Mapped", note: "" },
  { rule_id: 17, category: "Social Bar", when: "Social Bar", "in": "Any Parent", "if": "Any Layout (H/V) → Any Parent", action: "Set Size", parameters: "Scaling: Reset, Height: Auto, Bounding Width: 100%", summary: "Set Size | Scaling: Reset, Height: Auto, Bounding Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 18, category: "Text Box", when: "Text", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Width: 100%, Height: Auto", summary: "Set Size | Width: 100%, Height: Auto", priority: 1, status: "Mapped", note: "" },
  { rule_id: 19, category: "Text Mask / Marquee", when: "Text Mask | Text Marquee", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Keep, Font Size: Keep (ignore font algo), Max Width: 100%", summary: "Set Size | Scaling: Keep, Font Size: Keep (ignore font algo), Max Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 20, category: "Button", when: "Button", "in": "Any Parent", "if": "Any Layout (Text/Icon/Text+Icon) → Any Parent", action: "Set Size", parameters: "Scaling: Reset, Font Size: Reset, Width: Desktop value (max: 100%), Height: SPX", summary: "Set Size | Scaling: Reset, Font Size: Reset, Width: Desktop value (max: 100%), Height: SPX", priority: 1, status: "Mapped", note: "" },
  { rule_id: 21, category: "Box", when: "Box", "in": "Any Parent", "if": "Blank AND Width: Any, Height: 0–199px", action: "Set Size", parameters: "Width: 100%, Height: 100px", summary: "Set Size | Width: 100%, Height: 100px", priority: 1, status: "Mapped", note: "" },
  { rule_id: 22, category: "Box", when: "Box", "in": "Any Parent", "if": "Blank AND Width: Any, Height: 200px+", action: "Set Size", parameters: "Width: 100%, Height: 200px", summary: "Set Size | Width: 100%, Height: 200px", priority: 1, status: "Mapped", note: "" },
  { rule_id: 23, category: "Box", when: "Box", "in": "Section", "if": "Width: Any, Height: Any", action: "Set Size", parameters: "Width: 100px (min), Height: Auto", summary: "Set Size | Width: 100px (min), Height: Auto", priority: 2, status: "Mapped", note: "" },
  { rule_id: 24, category: "Section / System Container", when: "System Container", "in": "Section | Footer", "if": "Blank", action: "Set Size", parameters: "Height: 200px", summary: "Set Size | Height: 200px", priority: 2, status: "Mapped", note: "" },
  { rule_id: 25, category: "Section / System Container", when: "System Container", "in": "Section", "if": "Contains Elements", action: "Set Size", parameters: "Height: Auto (min: 200px)", summary: "Set Size | Height: Auto (min: 200px)", priority: 2, status: "Mapped", note: "" },
  { rule_id: 26, category: "Padding (R/L)", when: "Any Element", "in": "Any Parent", "if": "Any", action: "Set Padding", parameters: "Padding Left: 24px, Padding Right: 24px", summary: "Set Padding | Padding Left: 24px, Padding Right: 24px", priority: 1, status: "Mapped", note: "Overrides element sizing" },
  { rule_id: 27, category: "Box Margin T/B", when: "Any Element", "in": "Box", "if": "Is First", action: "Set Margin", parameters: "Margin Top: 24px", summary: "Set Margin | Margin Top: 24px", priority: 2, status: "Mapped", note: "" },
  { rule_id: 28, category: "Box Margin T/B", when: "Any Element", "in": "Box", "if": "Is Last", action: "Set Margin", parameters: "Margin Bottom: 24px", summary: "Set Margin | Margin Bottom: 24px", priority: 2, status: "Mapped", note: "" },
  { rule_id: 29, category: "Section Margin T/B", when: "Any Element", "in": "Section", "if": "Is First", action: "Set Margin", parameters: "Margin Top: 40px", summary: "Set Margin | Margin Top: 40px", priority: 2, status: "Mapped", note: "" },
  { rule_id: 30, category: "Section Margin T/B", when: "Any Element", "in": "Section", "if": "Is Last", action: "Set Margin", parameters: "Margin Bottom: 40px", summary: "Set Margin | Margin Bottom: 40px", priority: 2, status: "Mapped", note: "" },
  { rule_id: 31, category: "Containers (Complex)", when: "Repeater", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Width: 100% (mobile), Height: Auto", summary: "Set Size | Width: 100% (mobile), Height: Auto", priority: 1, status: "Mapped", note: "" },
  { rule_id: 32, category: "Containers (Complex)", when: "Lightbox", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Width: 100% (mobile), Height: Auto", summary: "Set Size | Width: 100% (mobile), Height: Auto", priority: 1, status: "Mapped", note: "" },
  { rule_id: 33, category: "Containers (Complex)", when: "Tabs", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Width: 100% (mobile), Height: Auto", summary: "Set Size | Width: 100% (mobile), Height: Auto", priority: 1, status: "Mapped", note: "" },
  { rule_id: 34, category: "Containers (Complex)", when: "Accordion", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Width: 100% (mobile), Height: Auto", summary: "Set Size | Width: 100% (mobile), Height: Auto", priority: 1, status: "Mapped", note: "" },
  { rule_id: 35, category: "Containers (Complex)", when: "Any Child Element", "in": "Any Parent", "if": "After Container Resize", action: "Set Size", parameters: "Apply: Existing Heuristics", summary: "Set Size | Apply: Existing Heuristics", priority: 1, status: "Mapped", note: "Recursive application. Recursive: applies to children of Repeater | Lightbox | Tabs | Accordion" },
  { rule_id: 36, category: "Forms / Additional", when: "Address Input", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 37, category: "Forms / Additional", when: "Text Input", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 38, category: "Forms / Additional", when: "Dropdowns", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 39, category: "Forms / Additional", when: "Text Box (Form)", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 40, category: "Forms / Additional", when: "Radio Buttons", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 41, category: "Forms / Additional", when: "Rich Text", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 42, category: "Forms / Additional", when: "Checkboxes", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 43, category: "Forms / Additional", when: "Date Picker", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 44, category: "Forms / Additional", when: "Multi Checkboxes", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 45, category: "Forms / Additional", when: "Signature", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 46, category: "Forms / Additional", when: "Tags", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 47, category: "Forms / Additional", when: "Upload Buttons", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 48, category: "Forms / Additional", when: "Ratings", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 49, category: "Forms / Additional", when: "Recaptcha", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 50, category: "Forms / Additional", when: "Sliders", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 51, category: "Forms / Additional", when: "Switch", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 52, category: "Forms / Additional", when: "Progress Bar", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 53, category: "Forms / Additional", when: "Breadcrumbs", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 54, category: "Forms / Additional", when: "Site Search", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 55, category: "Forms / Additional", when: "Audio Player", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Scaling: Reset, Width: 100%", summary: "Set Size | Scaling: Reset, Width: 100%", priority: 1, status: "Mapped", note: "" },
  { rule_id: 56, category: "Embed / Media", when: "Lottie Animation", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Width: 100% (mobile), Height: Aspect Ratio", summary: "Set Size | Width: 100% (mobile), Height: Aspect Ratio", priority: 1, status: "Mapped", note: "" },
  { rule_id: 57, category: "Embed / Media", when: "Video Box", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Width: 100% (mobile), Height: Aspect Ratio", summary: "Set Size | Width: 100% (mobile), Height: Aspect Ratio", priority: 1, status: "Mapped", note: "" },
  { rule_id: 58, category: "Embed / Media", when: "Transparent Video", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Width: 100% (mobile), Height: Aspect Ratio", summary: "Set Size | Width: 100% (mobile), Height: Aspect Ratio", priority: 1, status: "Mapped", note: "" },
  { rule_id: 59, category: "Embed / Media", when: "Single Video Player", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Width: 100% (mobile), Height: Aspect Ratio", summary: "Set Size | Width: 100% (mobile), Height: Aspect Ratio", priority: 1, status: "Mapped", note: "" },
  { rule_id: 60, category: "Embed / Media", when: "Custom Element", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Width: 100% (mobile), Height: Aspect Ratio", summary: "Set Size | Width: 100% (mobile), Height: Aspect Ratio", priority: 1, status: "Mapped", note: "" },
  { rule_id: 61, category: "Embed / Media", when: "Embed", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Width: 100% (mobile), Height: Aspect Ratio", summary: "Set Size | Width: 100% (mobile), Height: Aspect Ratio", priority: 1, status: "Mapped", note: "" },
  { rule_id: 62, category: "Google Maps", when: "Google Maps", "in": "Any Parent", "if": "Any", action: "Set Size", parameters: "Width: 100% (shrinks), Height: Absolute (= desktop value)", summary: "Set Size | Width: 100% (shrinks), Height: Absolute (= desktop value)", priority: 1, status: "Mapped", note: "" },
  { rule_id: 63, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 0–14px → Path A", action: "Set Font Size", parameters: "Font Size (PX): A", summary: "Set Font Size | Font Size (PX): A", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 64, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 15–19px → Path B", action: "Set Font Size", parameters: "Font Size (PX): B", summary: "Set Font Size | Font Size (PX): B", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 65, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 20–22px → Path C", action: "Set Font Size", parameters: "Font Size (PX): C", summary: "Set Font Size | Font Size (PX): C", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 66, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 23–26px → Path D", action: "Set Font Size", parameters: "Font Size (PX): D", summary: "Set Font Size | Font Size (PX): D", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 67, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 27–30px → Path E", action: "Set Font Size", parameters: "Font Size (PX): E", summary: "Set Font Size | Font Size (PX): E", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 68, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 19–34px → Path F", action: "Set Font Size", parameters: "Font Size (PX): F", summary: "Set Font Size | Font Size (PX): F", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 69, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 28–43px → Path G", action: "Set Font Size", parameters: "Font Size (PX): G", summary: "Set Font Size | Font Size (PX): G", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 70, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 47–64px → Path H", action: "Set Font Size", parameters: "Font Size (PX): H", summary: "Set Font Size | Font Size (PX): H", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 71, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 22–35px → Path I", action: "Set Font Size", parameters: "Font Size (PX): I", summary: "Set Font Size | Font Size (PX): I", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 72, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 71–78px → Path J", action: "Set Font Size", parameters: "Font Size (PX): J", summary: "Set Font Size | Font Size (PX): J", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 73, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 79–88px → Path K", action: "Set Font Size", parameters: "Font Size (PX): K", summary: "Set Font Size | Font Size (PX): K", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 74, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 87–93px → Path L", action: "Set Font Size", parameters: "Font Size (PX): L", summary: "Set Font Size | Font Size (PX): L", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 75, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 63–103px → Path M", action: "Set Font Size", parameters: "Font Size (PX): M", summary: "Set Font Size | Font Size (PX): M", priority: 1, status: "Needs Values", note: "Font Algo A–N values pending" },
  { rule_id: 76, category: "Font Algo", when: "Text | Button | Collapsible Text", "in": "Any Parent", "if": "Desktop Size: 90px+ → Path N", action: "Set Font Size", parameters: "Font Size: Auto", summary: "Set Font Size | Font Size: Auto", priority: 1, status: "Mapped", note: "" },
  { rule_id: 77, category: "Header & Menu", when: "System Container", "in": "Header", "if": "Blank", action: "Set Size", parameters: "Height: 70px", summary: "Set Size | Height: 70px", priority: 2, status: "Mapped", note: "" },
  { rule_id: 78, category: "Header & Menu", when: "System Container", "in": "Header", "if": "Has elements", action: "Set Size", parameters: "Height: Auto (min: 70px)", summary: "Set Size | Height: Auto (min: 70px)", priority: 2, status: "Mapped", note: "" },
  { rule_id: 79, category: "Header & Menu", when: "Any Element", "in": "Header | System Container", "if": "Any", action: "Set Margin", parameters: "Margin Top: 20px", summary: "Set Margin | Margin Top: 20px", priority: 2, status: "Mapped", note: "" },
  { rule_id: 80, category: "Header & Menu", when: "Hamburger Menu", "in": "Header", "if": "Element sizing", action: "Set Size", parameters: "Width: 20px, Height: 14px", summary: "Set Size | Width: 20px, Height: 14px", priority: 2, status: "Mapped", note: "" },
  { rule_id: 81, category: "Header & Menu", when: "Logo Component", "in": "Header", "if": "Logo aspect ratio", action: "Set Size", parameters: "Width: Auto (aspect ratio), Height: 70px", summary: "Set Size | Width: Auto (aspect ratio), Height: 70px", priority: 2, status: "Mapped", note: "" },
  { rule_id: 82, category: "Header & Menu", when: "Logo", "in": "Header", "if": "No menus → Width < 40px", action: "Set Margin", parameters: "Margin Left: 20px, Margin Right: 20px, Align: Left", summary: "Set Margin | Margin Left: 20px, Margin Right: 20px, Align: Left", priority: 2, status: "Mapped", note: "" },
  { rule_id: 83, category: "Header & Menu", when: "Any Other Element", "in": "Header", "if": "Width < 40px or > 2 elements", action: "Set Margin", parameters: "Position: Next available inward adjacent row, Align: Center", summary: "Set Margin | Position: Next available inward adjacent row, Align: Center", priority: 2, status: "Mapped", note: "" },
  { rule_id: 84, category: "Header & Menu", when: "Hamburger Menu", "in": "Header", "if": "Width < 40px → < 3 elements in row", action: "Set Margin", parameters: "Margin Left: 20px, Align: Left (swapped)", summary: "Set Margin | Margin Left: 20px, Align: Left (swapped)", priority: 2, status: "Mapped", note: "" },
  { rule_id: 85, category: "Header & Menu", when: "1st Element in Row", "in": "Header", "if": "< 3 elements in first row", action: "Set Margin", parameters: "Margin Left: 20px, Align: Left", summary: "Set Margin | Margin Left: 20px, Align: Left", priority: 2, status: "Mapped", note: "" },
  { rule_id: 86, category: "Header & Menu", when: "2nd Element in Row", "in": "Header", "if": "< 3 elements in first row", action: "Set Margin", parameters: "Margin Right: 20px, Align: Right", summary: "Set Margin | Margin Right: 20px, Align: Right", priority: 2, status: "Mapped", note: "" },
  { rule_id: 87, category: "Header & Menu", when: "Header Row Elements", "in": "Header", "if": "≥ 3 elements in first row", action: "Set Margin", parameters: "Hamburger: Margin Left 20px, Others: Next Row, Align: Center", summary: "Set Margin | Hamburger: Margin Left 20px, Others: Next Row, Align: Center", priority: 2, status: "Mapped", note: "" },
  { rule_id: 88, category: "Header & Menu", when: "Logo + Hamburger", "in": "Header", "if": "Only 2 elements: Logo + Hamburger", action: "Set Margin", parameters: "Logo: Margin Left 20px, Hamburger: Margin Right 20px", summary: "Set Margin | Logo: Margin Left 20px, Hamburger: Margin Right 20px", priority: 2, status: "Mapped", note: "" },
  { rule_id: 89, category: "Header & Menu", when: "Two Elements (no hamburger)", "in": "Header", "if": "2 elements in row, no hamburger", action: "Set Margin", parameters: "1st: Margin Left 20px, Align Left, 2nd: Margin Right 20px, Align Right", summary: "Set Margin | 1st: Margin Left 20px, Align Left, 2nd: Margin Right 20px, Align Right", priority: 2, status: "Mapped", note: "" },
  { rule_id: 90, category: "Pinned", when: "Any Pinned Element", "in": "Any Parent", "if": "Group 1 (Expand/Top Right/Anchor Right/Abs Left) → H-Axis → 0 Type", action: "Set Pinned", parameters: "—", summary: "Set Pinned", priority: 1, status: "Mapped", note: "" },
  { rule_id: 91, category: "Pinned", when: "Any Pinned Element", "in": "Any Parent", "if": "Group 1 → H-Axis → Pipe + Video", action: "Set Pinned", parameters: "Offset: left/top/Size (pinned)", summary: "Set Pinned | Offset: left/top/Size (pinned)", priority: 1, status: "Mapped", note: "" },
  { rule_id: 92, category: "Pinned", when: "Any Pinned Element", "in": "Any Parent", "if": "Group 1 → H-Axis → Any", action: "Set Pinned", parameters: "—", summary: "Set Pinned", priority: 1, status: "Mapped", note: "" },
  { rule_id: 93, category: "Pinned", when: "Any Pinned Element", "in": "Any Parent", "if": "Group 2 (Above Center/Text Center) → 1 Row → 0 Type", action: "Set Pinned", parameters: "—", summary: "Set Pinned", priority: 1, status: "Mapped", note: "" },
  { rule_id: 94, category: "Pinned", when: "Any Pinned Element", "in": "Any Parent", "if": "Group 2 → > 1 Row → Diff < 17px", action: "Set Pinned", parameters: "Offset: left/top/Size (pinned)", summary: "Set Pinned | Offset: left/top/Size (pinned)", priority: 1, status: "Mapped", note: "" },
  { rule_id: 95, category: "Pinned", when: "Any Pinned Element", "in": "Any Parent", "if": "Group 2 → > 1 Row → 7px + 300px", action: "Set Pinned", parameters: "Offset: left/top/Size (pinned)", summary: "Set Pinned | Offset: left/top/Size (pinned)", priority: 1, status: "Mapped", note: "" },
  { rule_id: 96, category: "Pinned", when: "Any Pinned Element", "in": "Any Parent", "if": "Group 3 (Left Center/Triple Center) → H-Axis → 0 Type", action: "Set Pinned", parameters: "—", summary: "Set Pinned", priority: 1, status: "Mapped", note: "" },
  { rule_id: 97, category: "Pinned", when: "Any Pinned Element", "in": "Any Parent", "if": "Group 3 → H-Axis → Pipe + 300px", action: "Set Pinned", parameters: "Offset: left/top/Size (pinned)", summary: "Set Pinned | Offset: left/top/Size (pinned)", priority: 1, status: "Mapped", note: "" },
  { rule_id: 98, category: "New Heuristics", when: "Box", "in": "Any Parent", "if": "Width = parent width", action: "Set Size", parameters: "Width: 390px, Height: Auto", summary: "Set Size | Width: 390px, Height: Auto", priority: 1, status: "Mapped", note: "" },
  { rule_id: 99, category: "New Heuristics", when: "Image", "in": "Section", "if": "Width = parent width", action: "Set Size", parameters: "Width: 390px, Height: 400px (min)", summary: "Set Size | Width: 390px, Height: 400px (min)", priority: 2, status: "Mapped", note: "" },

  // ── Repeater — Layout Type ────────────────────────────────────────────────
  { rule_id: 100, category: "Repeater — Layout", when: "Repeater", "in": "Any Parent", "if": "Layout: Cards → Any desktop width", action: "Set Size", parameters: "Width: 100%, Items Per Row: 1, Column Min Width: mobile viewport, Height: Auto", summary: "Set Size | Width: 100%, Items Per Row: 1, Column Min Width: mobile viewport, Height: Auto", priority: 1, status: "Mapped", note: "Cards layout collapses to 1 item per row on mobile" },
  { rule_id: 101, category: "Repeater — Layout", when: "Repeater", "in": "Any Parent", "if": "Layout: List → Any desktop width", action: "Set Size", parameters: "Width: 100%, Items Per Row: 1 (forced), Height: Auto", summary: "Set Size | Width: 100%, Items Per Row: 1 (forced), Height: Auto", priority: 1, status: "Mapped", note: "List layout always single column" },
  { rule_id: 102, category: "Repeater — Layout", when: "Repeater", "in": "Any Parent", "if": "Layout: Grid → Any desktop width", action: "Set Size", parameters: "Width: 100%, Items Per Row: 4+ columns → 2, 1–3 columns → 1, Column Min Width: mobile viewport, Height: Auto", summary: "Set Size | Width: 100%, Items Per Row: 4+ columns → 2, 1–3 columns → 1, Column Min Width: mobile viewport, Height: Auto", priority: 1, status: "Mapped", note: "Grid: 1–3 columns → 1, 4+ columns → 2 on mobile" },
  { rule_id: 103, category: "Repeater — Layout", when: "Repeater", "in": "Any Parent", "if": "Layout: Slider → Any desktop width", action: "Set Size", parameters: "Width: 100%, Items Per Row: 1, Scroll Snap: Start, Scrollbar: Hide", summary: "Set Size | Width: 100%, Items Per Row: 1, Scroll Snap: Start, Scrollbar: Hide", priority: 1, status: "Mapped", note: "Slider layout becomes horizontally scrollable strip on mobile" },

  // ── Repeater — Items Per Row ───────────────────────────────────────────────
  { rule_id: 104, category: "Repeater — Items Per Row", when: "Repeater", "in": "Any Parent", "if": "Items Per Row: Enabled AND value ≥ 4 on desktop", action: "Set Size", parameters: "Items Per Row: 2", summary: "Set Size | Items Per Row: 2", priority: 1, status: "Mapped", note: "Reduce items per row to 2 for mobile readability" },
  { rule_id: 105, category: "Repeater — Items Per Row", when: "Repeater", "in": "Any Parent", "if": "Items Per Row: Enabled AND value = 2–3 on desktop", action: "Set Size", parameters: "Items Per Row: 1", summary: "Set Size | Items Per Row: 1", priority: 1, status: "Mapped", note: "2–3 columns collapse to 1 on mobile" },
  { rule_id: 106, category: "Repeater — Items Per Row", when: "Repeater", "in": "Any Parent", "if": "Items Per Row: Disabled (auto-fit by column min width)", action: "Set Size", parameters: "Column Min Width: 100% (mobile viewport)", summary: "Set Size | Column Min Width: 100% (mobile viewport)", priority: 1, status: "Mapped", note: "Auto-fit mode: force full width so 1 item fills the row" },

  // ── Repeater — Column & Row Sizing ─────────────────────────────────────────
  { rule_id: 107, category: "Repeater — Column & Row Sizing", when: "Repeater", "in": "Any Parent", "if": "Column Min Width: Any desktop value", action: "Set Min Height", parameters: "Column Min Width: 280px", summary: "Set Min Height | Column Min Width: 280px", priority: 2, status: "Mapped", note: "Prevent cards from becoming too narrow on mobile" },
  { rule_id: 108, category: "Repeater — Column & Row Sizing", when: "Repeater", "in": "Any Parent", "if": "Keep Rows Equal: On", action: "Set Size", parameters: "Row Min Height: Keep desktop value (min: 200px)", summary: "Set Size | Row Min Height: Keep desktop value (min: 200px)", priority: 1, status: "Mapped", note: "Equal-row mode preserves row height; apply minimum 200px floor" },
  { rule_id: 109, category: "Repeater — Column & Row Sizing", when: "Repeater", "in": "Any Parent", "if": "Keep Rows Equal: Off", action: "Set Size", parameters: "Row Min Height: Auto", summary: "Set Size | Row Min Height: Auto", priority: 1, status: "Mapped", note: "Variable-height rows: let content drive height" },

  // ── Repeater — Single Row Behavior ─────────────────────────────────────────
  { rule_id: 110, category: "Repeater — Single Row", when: "Repeater", "in": "Any Parent", "if": "Single Row AND When There's A Single Row: Stretch Columns To Fill Row", action: "Set Size", parameters: "Width: 100%, Stretch: Fill Row", summary: "Set Size | Width: 100%, Stretch: Fill Row", priority: 2, status: "Mapped", note: "When only one row: stretch items to fill full width" },
  { rule_id: 111, category: "Repeater — Single Row", when: "Repeater", "in": "Any Parent", "if": "Single Row AND When There's A Single Row: Keep Empty Columns", action: "Set Size", parameters: "Width: 100%, Empty Columns: Keep", summary: "Set Size | Width: 100%, Empty Columns: Keep", priority: 2, status: "Mapped", note: "When only one row: preserve column count structure" },

  // ── Repeater — Spacing & Padding ───────────────────────────────────────────
  { rule_id: 112, category: "Repeater — Spacing & Padding", when: "Repeater", "in": "Any Parent", "if": "Desktop Horizontal Spacing: > 24px", action: "Set Spacing", parameters: "Horizontal Spacing: 16px", summary: "Set Spacing | Horizontal Spacing: 16px", priority: 1, status: "Mapped", note: "Reduce inter-item horizontal gap on mobile" },
  { rule_id: 113, category: "Repeater — Spacing & Padding", when: "Repeater", "in": "Any Parent", "if": "Desktop Vertical Spacing: > 24px", action: "Set Spacing", parameters: "Vertical Spacing: 16px", summary: "Set Spacing | Vertical Spacing: 16px", priority: 1, status: "Mapped", note: "Reduce inter-item vertical gap on mobile" },
  { rule_id: 114, category: "Repeater — Spacing & Padding", when: "Repeater", "in": "Any Parent", "if": "Desktop Padding: > 12px", action: "Set Padding", parameters: "Padding: 12px", summary: "Set Padding | Padding: 12px", priority: 1, status: "Mapped", note: "Reduce repeater outer padding on mobile" },

  // ── Repeater — Overflow & Scroll ───────────────────────────────────────────
  { rule_id: 115, category: "Repeater — Overflow & Scroll", when: "Repeater", "in": "Any Parent", "if": "Overflow Content: Show AND Layout: Slider", action: "Set Size", parameters: "Overflow: Show, Scrollbar: Hide, Scroll Snap: Start", summary: "Set Size | Overflow: Show, Scrollbar: Hide, Scroll Snap: Start", priority: 1, status: "Mapped", note: "Slider mode: hide scrollbar, enable snap for swipe UX" },
  { rule_id: 116, category: "Repeater — Overflow & Scroll", when: "Repeater", "in": "Any Parent", "if": "Overflow Content: Hide AND Layout ≠ Slider", action: "Set Size", parameters: "Overflow: Hide", summary: "Set Size | Overflow: Hide", priority: 2, status: "Mapped", note: "Non-slider: keep overflow hidden to avoid scroll bleed" },

  // ── Repeater — Alignment ───────────────────────────────────────────────────
  { rule_id: 120, category: "Repeater — Alignment", when: "Repeater", "in": "Any Parent", "if": "Alignment: Left (desktop)", action: "Set Alignment", parameters: "Value: Left", summary: "Set Alignment | Value: Left", priority: 2, status: "Mapped", note: "" },
  { rule_id: 121, category: "Repeater — Alignment", when: "Repeater", "in": "Any Parent", "if": "Alignment: Center (desktop)", action: "Set Alignment", parameters: "Value: Center", summary: "Set Alignment | Value: Center", priority: 2, status: "Mapped", note: "" },

  // ── Repeater Cell Children ─────────────────────────────────────────────────
  { rule_id: 117, category: "Repeater Cell", when: "Repeater Cell", "in": "Repeater", "if": "Any", action: "Set Size", parameters: "Width: 100%, Height: Auto", summary: "Set Size | Width: 100%, Height: Auto", priority: 1, status: "Mapped", note: "Each cell fills its column and auto-sizes by content" },
  { rule_id: 118, category: "Repeater Cell", when: "Repeater Cell", "in": "Repeater", "if": "Desktop Padding: Any", action: "Set Padding", parameters: "Padding: 16px (all sides)", summary: "Set Padding | Padding: 16px (all sides)", priority: 1, status: "Mapped", note: "Inner cell padding reduced for mobile" },
  { rule_id: 119, category: "Repeater Cell", when: "Any Child Element", "in": "Repeater Cell", "if": "After Repeater resize", action: "Set Size", parameters: "Apply: Existing Heuristics", summary: "Set Size | Apply: Existing Heuristics", priority: 1, status: "Mapped", note: "Recursive: apply standard heuristics to all children inside each cell" },
  { rule_id: 122, category: "Repeater Cell", when: "Any Child Element", "in": "Repeater Cell", "if": "Is First", action: "Set Margin", parameters: "Margin Top: 40px", summary: "Set Margin | Margin Top: 40px", priority: 2, status: "Mapped", note: "First child in repeater cell gets top margin" },
  { rule_id: 123, category: "Repeater Cell", when: "Any Child Element", "in": "Repeater Cell", "if": "Is Last", action: "Set Margin", parameters: "Margin Bottom: 40px", summary: "Set Margin | Margin Bottom: 40px", priority: 2, status: "Mapped", note: "Last child in repeater cell gets bottom margin" },

  // ── Pinned to Section ──────────────────────────────────────────────────────
  { rule_id: 124, category: "Pinned to Section", when: "Any Pinned Element", "in": "Section", "if": "Pinned Position: Sidebar (Left/Right)", action: "Set Pinned", parameters: "Unpin → Position: Inline (content flow)", summary: "Set Pinned | Unpin → Position: Inline (content flow)", priority: 1, status: "Mapped", note: "Pinned sidebars convert to inline content blocks on mobile" },
  { rule_id: 125, category: "Pinned to Section", when: "Any Pinned Element", "in": "Section", "if": "Pinned Position: Top AND Height ≥ 60px", action: "Set Size", parameters: "Height: 48px", summary: "Set Size | Height: 48px", priority: 1, status: "Mapped", note: "Reduce tall pinned toolbars to conserve mobile viewport" },
  { rule_id: 126, category: "Pinned to Section", when: "Any Pinned Element", "in": "Section", "if": "Multiple Pinned (≥ 2 siblings) AND Direction: Horizontal", action: "Set Pinned", parameters: "Overflow: Scroll (horizontal strip), Scrollbar: Hide", summary: "Set Pinned | Overflow: Scroll (horizontal strip), Scrollbar: Hide", priority: 1, status: "Mapped", note: "Multiple pinned items → horizontal scrollable strip" },
  { rule_id: 127, category: "Pinned to Section", when: "Any Pinned Element", "in": "Section", "if": "Pinned Position: Top AND Has Children ≥ 3", action: "Set Pinned", parameters: "Collapse on scroll: Show icons only, Hide labels", summary: "Set Pinned | Collapse on scroll: Show icons only, Hide labels", priority: 2, status: "Mapped", note: "Full toolbar collapses to icon-only bar after scroll threshold" },
  { rule_id: 128, category: "Pinned to Section", when: "Any Pinned Element", "in": "Section", "if": "Pinned Position: Bottom (CTA / Action Bar)", action: "Set Pinned", parameters: "Keep Pinned: Bottom, Z-Index: 100", summary: "Set Pinned | Keep Pinned: Bottom, Z-Index: 100", priority: 2, status: "Mapped", note: "Bottom-pinned CTAs stay fixed for thumb-friendly mobile UX" },
  { rule_id: 129, category: "Pinned to Section", when: "Any Pinned Element", "in": "Section", "if": "Pinned AND Overlaps Section Content", action: "Set Pinned", parameters: "Z-Index: 50", summary: "Set Pinned | Z-Index: 50", priority: 2, status: "Mapped", note: "Pinned elements sit above content but below modals/overlays" },
  { rule_id: 130, category: "Pinned to Section", when: "Any Pinned Element", "in": "Section", "if": "Width ≠ 100% AND Position ≠ Sidebar", action: "Set Size", parameters: "Width: 100%", summary: "Set Size | Width: 100%", priority: 1, status: "Mapped", note: "Non-sidebar pinned elements expand to full width on mobile" },
  { rule_id: 131, category: "Pinned to Section", when: "Any Pinned Element", "in": "Section", "if": "Pinned Position: Top AND Scroll Offset ≥ 200px", action: "Set Visibility", parameters: "Fade-in: Opacity transition (0 → 1, 300ms)", summary: "Set Visibility | Fade-in: Opacity transition (0 → 1, 300ms)", priority: 2, status: "Mapped", note: "Avoid persistent bars — show after meaningful scroll depth" }
]

export const COLUMNS = [
  { key: 'rule_id', label: 'ID', className: 'col-id' },
  { key: 'category', label: 'Category', className: 'col-category' },
  { key: 'when', label: 'When', className: 'col-when' },
  { key: 'in', label: 'In', className: 'col-in' },
  { key: 'if', label: 'If', className: 'col-if' },
  { key: 'action', label: 'Action', className: 'col-action' },
  { key: 'parameters', label: 'Parameters', className: 'col-params' },
  { key: 'priority', label: 'Pri', className: 'col-priority' },
  { key: 'status', label: 'Status', className: 'col-status' },
  { key: 'note', label: 'Note', className: 'col-note' }
]

export const CATEGORIES = [...new Set(SEED_DATA.map(r => r.category))]
export const ACTIONS = [...new Set(SEED_DATA.map(r => r.action))]
export const CONTEXTS = [...new Set(SEED_DATA.map(r => r.in))]
export const STATUSES = ['Mapped', 'Needs Values', 'Dev in Progress', 'Done', 'On Hold', 'Rejected']
export const PRIORITIES = [1, 2, 3]

export const CANONICAL_ACTIONS = ["Set Size","Set Min Height","Set Margin","Set Padding","Set Alignment","Set Rotation","Set Visibility","Set Spacing","Set Pinned","Set Font Size","Set OOG"]
export const CANONICAL_COMPONENTS = ["Any Element","Any Container","Any Child Element","Any Pinned Element","Section","Header","Footer","System Container","Easy Grid","CSS Grid","Cell","Box","Repeater","Lightbox","Tabs","Accordion","Image","Lottie Animation","Video Box","Transparent Video","Single Video Player","Custom Element","Embed","Google Maps","Text","Text Mask","Text Marquee","Collapsible Text","Button","Social Bar","Hamburger Menu","Shape","Horizontal Line","Vertical Line","List Item"]
export const CANONICAL_CONTEXTS = ["Any Parent","Section","Header","Footer","Box","Header | System Container","Section | Footer","Section > Easy Grid"]